### ISSUE TITLE
I can't download checkpoint

### ISSUE THREAD

**Issue by How-to-say** [shinya7y/UniverseNet#40]
when i run 'mim download mmdet --config yolov3_mobilenetv2_320_300e_coco'
it error,
Traceback (most recent call last):
  File "/root/miniconda3/envs/universe/bin/mim", line 8, in <module>
    sys.exit(cli())
  File "/root/miniconda3/envs/universe/lib/python3.8/site-packages/click/core.py", line 1161, in __call__
    return self.main(*args, **kwargs)
  File "/root/miniconda3/envs/universe/lib/python3.8/site-packages/click/core.py", line 1082, in main
    rv = self.invoke(ctx)
  File "/root/miniconda3/envs/universe/lib/python3.8/site-packages/click/core.py", line 1697, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/root/miniconda3/envs/universe/lib/python3.8/site-packages/click/core.py", line 1443, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/root/miniconda3/envs/universe/lib/python3.8/site-packages/click/core.py", line 788, in invoke
    return __callback(*args, **kwargs)
  File "/root/miniconda3/envs/universe/lib/python3.8/site-packages/mim/commands/download.py", line 70, in cli
    download(package, configs, dest_root, check_certificate, dataset)
  File "/root/miniconda3/envs/universe/lib/python3.8/site-packages/mim/commands/download.py", line 107, in download
    return _download_configs(package, configs, dest_root,
  File "/root/miniconda3/envs/universe/lib/python3.8/site-packages/mim/commands/download.py", line 132, in _download_configs
    model_info = get_model_info(
  File "/root/miniconda3/envs/universe/lib/python3.8/site-packages/mim/commands/search.py", line 189, in get_model_info
    dataframe = convert2df(metadata)
  File "/root/miniconda3/envs/universe/lib/python3.8/site-packages/mim/commands/search.py", line 427, in convert2df
    for key, value in name2collection[collection_name].items():
KeyError: 'Cascade Mask R-CNN'

**Comment by shinya7y** [comment]
It seems a bug in mmdet 2.25.0, fixed in 2.25.1.
The fix in the following PR may resolve the issue.
https://github.com/open-mmlab/mmdetection/pull/8240
